name: http_multi_server
version: 3.2.2-dev
description: >-
  A dart:io HttpServer wrapper that handles requests from multiple servers.
repository: https://github.com/dart-lang/http_multi_server

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.5.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  http: ^0.13.0
  shelf: ^1.4.0
  test: ^1.16.0
