name: http_multi_server
version: 3.2.2-wip
description: >-
  A dart:io HttpServer wrapper that handles requests from multiple servers.
repository: https://github.com/dart-lang/http_multi_server

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.5.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  http: ^1.0.0
  shelf: ^1.4.0
  test: ^1.16.0
